#!/bin/bash

cd $1
shift

for arg in "$@"
do
 if [ ".java" == .${arg##*.} ]
 then
  echo Checking $arg
   if grep -l "	" $arg
   then
    echo "Tab characters not allowed!  Use spaces or \\t instead."
    exit 1
   fi
 fi
done

exit 0
